language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=2.0.9
  - DJANGO=2.1.3
  - DJANGO=2.2.9

install:
  - pip install Django==$DJANGO times da-vinci pillow redis shortuuid
  - sudo apt-get install -qq optipng

script: make test
services: redis
