language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11.13
  - DJANGO=2.0.9
  - DJANGO=2.1.3

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0.9
    - python: "2.7"
      env: DJANGO=2.1.3


install:
  - pip install Django==$DJANGO times da-vinci pillow redis shortuuid
  - sudo apt-get install -qq optipng

script: make test
services: redis
